export const handleError = (error: unknown): void => {
  throw error
}
